#Esse workflow vai disparar automaticamente em push e pull_request para a branch main, 
#que é um padrão suportado pela sintaxe oficial do GitHub Actions

name: CI - FastAPI

on:
  push:
  pull_request:
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar testes
        run: python -m pytest tests/test_auth.py